using System;
using System.Collections.Generic;

namespace EfCoreMcp.Core.Domain;

/// <summary>
/// Represents the status of migrations including applied migrations, pending migrations, and whether the model has drifted.
/// </summary>
/// <param name="Applied">List of migration names that have been applied to the database.</param>
/// <param name="Pending">List of migration names that have not been applied to the database.</param>
/// <param name="HasPendingModelChanges">Whether the current model differs from the last migration snapshot.</param>
public sealed class MigrationStatus : IEquatable<MigrationStatus>
{
    public IReadOnlyList<string> Applied { get; }
    public IReadOnlyList<string> Pending { get; }
    public bool HasPendingModelChanges { get; }

    public MigrationStatus(
        IReadOnlyList<string> applied,
        IReadOnlyList<string> pending,
        bool hasPendingModelChanges)
    {
        ArgumentNullException.ThrowIfNull(applied);
        ArgumentNullException.ThrowIfNull(pending);
        Applied = applied;
        Pending = pending;
        HasPendingModelChanges = hasPendingModelChanges;
    }

    public bool Equals(MigrationStatus? other)
    {
        if (ReferenceEquals(null, other)) return false;
        if (ReferenceEquals(this, other)) return true;

        return HasPendingModelChanges == other.HasPendingModelChanges
            && EqualityComparer<IReadOnlyList<string>>.Default.Equals(Applied, other.Applied)
            && EqualityComparer<IReadOnlyList<string>>.Default.Equals(Pending, other.Pending);
    }

    public override bool Equals(object? obj) => Equals(obj as MigrationStatus);

    public override int GetHashCode()
    {
        return HashCode.Combine(
            EqualityComparer<IReadOnlyList<string>>.Default.GetHashCode(Applied),
            EqualityComparer<IReadOnlyList<string>>.Default.GetHashCode(Pending),
            HasPendingModelChanges);
    }

    public static bool operator ==(MigrationStatus? left, MigrationStatus? right) => Equals(left, right);

    public static bool operator !=(MigrationStatus? left, MigrationStatus? right) => !Equals(left, right);
}

/// <summary>
/// Represents the difference between the current model and the migration snapshot.
/// </summary>
/// <param name="HasDifferences">Whether any differences exist between the current model and the snapshot.</param>
/// <param name="Operations">List of migration operations that would be generated by a new migration.</param>
public sealed record ModelDiff(
    bool HasDifferences,
    IReadOnlyList<ModelDiffOperation> Operations);

/// <summary>
/// Represents a single difference between the current model and the migration snapshot.
/// </summary>
/// <param name="OperationType">The type of migration operation (e.g., CreateTable, DropColumn, AlterColumn).</param>
/// <param name="Table">The table affected by the operation, if applicable.</param>
/// <param name="Schema">The schema of the table, if applicable.</param>
/// <param name="Name">The name of the column, index, or other entity being modified.</param>
/// <param name="Description">Human-readable description of the operation.</param>
/// <param name="IsDestructive">Whether this operation is destructive (e.g., drops data or changes schema in a breaking way).</param>
public sealed record ModelDiffOperation(
    string OperationType,
    string? Table,
    string? Schema,
    string? Name,
    string Description,
    bool IsDestructive);
